name: Build yaml

on:
  push:
    branches: [ "main" ]

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      
    - name: Setup Docker Buildx
    - uses: docker/setup-buildx-action@v2

    # - name: Build the Docker argument
    #   run: docker --build-arg RUNNER_VERSION=2.319.1 .
    - name: Build the Docker image  
      run: docker build --build-arg RUNNER_VERSION=2.319.1 -t supdude/tr-poc:l1 .

    - name: Push to Dockerhub
      run: docker push supdude/tr-poc:l1
    - name: Pull Docker image
      run: sudo docker pull supdude/tr-poc:l1